### ISSUE TITLE
npx webpack error

### ISSUE THREAD

**Issue by EvansPM** [nornagon/optimize-paths-svg-example#1]
After `npm install` then `npx webpack`
i got:
```
λ npx webpack
(node:15216) UnhandledPromiseRejectionWarning: Error: No valid exports main found for 'C:\Users\ME\Desktop\optimize-paths-svg-example-main\node_modules\colorette'
    at resolveExportsTarget (internal/modules/cjs/loader.js:622:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (C:\Users\ME\Desktop\optimize-paths-svg-example-main\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.get colors [as colors] (C:\Users\ME\Desktop\optimize-paths-svg-example-main\node_modules\webpack-cli\lib\utils\index.js:3:16)
    at Object.error (C:\Users\ME\Desktop\optimize-paths-svg-example-main\node_modules\webpack-cli\lib\utils\logger.js:5:58)
(node:15216) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:15216) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by nornagon** [comment]
Hm, I can't reproduce this.

```
$ npm install
[...]
$ npx webpack
asset main.js 24.9 KiB [emitted] [minimized] (name: main) 1 related asset
runtime modules 937 bytes 4 modules
modules by path ./node_modules/ 53.1 KiB
  modules by path ./node_modules/flatten-svg/dist/*.js 39.1 KiB
    ./node_modules/flatten-svg/dist/index.js 282 bytes [built] [code generated]
    ./node_modules/flatten-svg/dist/svg-to-paths.js 8.92 KiB [built] [code generated]
    ./node_modules/flatten-svg/dist/path-data-polyfill.js 29.9 KiB [built] [code generated]
  modules by path ./node_modules/optimize-paths/dist/*.js 5.9 KiB
    ./node_modules/optimize-paths/dist/index.js 3.9 KiB [built] [code generated]
    ./node_modules/optimize-paths/dist/vec.js 403 bytes [built] [code generated]
    ./node_modules/optimize-paths/dist/knn.js 1.61 KiB [built] [code generated]
  ./node_modules/rbush/rbush.min.js 6.31 KiB [built] [code generated]
  ./node_modules/tinyqueue/index.js 1.73 KiB [built] [code generated]
./src/index.js 2.8 KiB [built] [code generated]

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value.
Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

webpack 5.39.0 compiled with 1 warning in 5312 ms
```

Can you confirm this is happening on a clean clone? e.g. delete the directory, run `git clone` again, cd into it and run the above commands. Do you still get the same behavior?

If so, what version of node / npm are you using? What OS are you on?
